---
analyzer:
  skip_excluded: true
  package_managers:
    GradleInspector:
      options:
        # HACK: Bypass foojay Temurin JDK auto-provisioning (broken since 2026-10-06,
        # see https://github.com/foojayio/discoapi/issues/165) by downloading a
        # fixed Temurin 21 build directly. Overrides the ai-dial-ci provided javaVersion option
        # TODO: Remove this once upgraded to a newer Gradle version and/or Java version, or when the foojay API is fixed
        customJdkUrl: "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jdk_x64_linux_hotspot_21.0.12.1_1.tar.gz"
excludes:
  scopes:
    - pattern: "annotationProcessor"
      reason: "BUILD_DEPENDENCY_OF"
      comment: "Packages to process code annotations only."
    - pattern: "checkstyle"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for static code analysis only."
    - pattern: "lombok"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages from Project Lombok only."
    - pattern: "test.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."
