# Alphabetically sorted

apache_commons_version=3.18.0
apache_httpclient5_version=5.4.3
apache_httpcore5_version=5.4.3
apache_jclouds_version=2.7.3
auth0_java_version=4.4.0
auth0_jwks_version=0.22.1
aws_sdk_v2_version=2.46.8
azure_security_keyvault_keys_version=4.10.6
azure_version=1.18.2
codehaus_janino_version=3.1.10
commons_io_version=2.14.0
epam_deltix_gflog_version=3.0.6
github_codemonstur_embedded_redis=1.4.3
glassfish_jakarta_version=4.0.2
google_auth_version=1.23.0
google_cloud_kms_version=2.77.0
google_cloud_version=2.60.0
google_protobuf_version=3.25.5
guava_version=33.4.8-jre
hibernate_validator_version=8.0.0.Final
jackson_core_version=2.21.5
mcp_sdk_version=1.1.2
jsonschema_generator_version=4.38.0
jakarta_annotation_api_version=3.0.0
jakarta_validation_version=3.0.2
jayway_jsonpath_version=2.9.0
junit_platform_version=1.13.4
junit_version=5.9.3
logback_version=1.5.34
logstash_logback_version=7.4
micrometer_version=1.16.6
mockito_version=5.7.0
netty_version=4.1.136.Final
networknt_version=1.5.2
nimbusds_version=11.27.1
opentelemetry_instrumentation_version=2.28.0-alpha
opentelemetry_version=1.62.0
redisson_version=3.27.0
slf4j_version=2.0.9
spotbugs_version=4.9.4
squareup_okhttp3_version=4.12.0
swagger_core_version=2.2.45
vertx_version=4.5.27
