dependencies {
    // Project dependencies (internal modules)
    implementation project(':config')
    implementation project(':storage')

    // External dependencies
    implementation("com.fasterxml.jackson.core:jackson-databind:${jackson_core_version}")
    implementation("com.google.guava:guava:${guava_version}")
    implementation("com.nimbusds:oauth2-oidc-sdk:${nimbusds_version}")
    implementation("org.apache.httpcomponents.client5:httpclient5:${apache_httpclient5_version}")
    implementation("org.slf4j:slf4j-api:${slf4j_version}")

    // Test dependencies
    testImplementation("org.junit.jupiter:junit-jupiter-api:${junit_version}")
    testImplementation("org.junit.jupiter:junit-jupiter-params:${junit_version}")
    testImplementation("org.mockito:mockito-core:${mockito_version}")
    testImplementation("org.mockito:mockito-junit-jupiter:${mockito_version}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junit_version}")
}

test {
    testLogging {
        events "passed", "skipped", "failed", "standardOut", "standardError"
        exceptionFormat = "full"
    }
    useJUnitPlatform()
}