dependencies {
    implementation project(':config')

    implementation 'org.slf4j:slf4j-api:2.0.9'
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.4.3'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'com.nimbusds:oauth2-oidc-sdk:11.27.1'
}