image:
  pullPolicy: Always
  registry: registry-dev.deltixhub.com
  repository: ai/dial/dial-proxy
  tag: development
  pullSecrets: 
    - epm-rtc-registry-dev

replicaCount: 1
resources:
  limits:
    cpu: 0.25
    memory: 512Gi
  requests:
    cpu: 0.1
    memory: 256Mi

podAnnotations:
  autorestart: '{{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC" }}'


ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-path: "/aiproxy/status200"
    alb.ingress.kubernetes.io/healthcheck-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/target-group-attributes: "stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=86400"
    alb.ingress.kubernetes.io/load-balancer-attributes: "routing.http2.enabled=true"
    alb.ingress.kubernetes.io/listen-ports: '[{ "HTTP" : 80, "HTTPS" : 443 }]'
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-Ext-2018-06"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-north-1:725751206603:certificate/373e8fd1-088e-4022-adf1-5f3e7820fb4a"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/group.name: "allow-all"
  hosts:
    - dial-proxy.staging.deltixhub.io

serviceAccount:
  create: true

env:
  proxy.config.files: '["/mnt/secrets-store/dialConfig","/mnt/secrets-store/dialKey","/mnt/secrets-store/dialAida"]'

extraVolumes:
  - name: secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: vault-dial-config-dev

extraVolumeMounts:
  - name: secrets
    readOnly: true
    mountPath: /mnt/secrets-store

bedrock:
  enabled: false

vertex:
  enabled: false

assistant:
  enabled: false

logger:
  enabled: true

service:
  extraPorts:
    - name: metrics
      port: 9464
      targetPort: 9464

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    port: metrics
    # path: "/metrics"   # default
    interval: "10s"
    labels:
      monitoring: application

extraDeploy:
  - apiVersion: secrets-store.csi.x-k8s.io/v1
    kind: SecretProviderClass
    metadata:
      name: vault-dial-config-dev
    spec:
      provider: vault
      parameters:
        roleName: "dial"
        vaultAddress: 'https://vault.vault:8200'
        vaultCACertPath: '/vault/tls/ca.crt'
        objects: |
          - objectName: "dialConfig"
            secretPath: "dial/data/development"
            secretKey: "config"
          - objectName: "dialKey"
            secretPath: "dial/data/development"
            secretKey: "keys"
          - objectName: "dialAida"
            secretPath: "dial/data/aida"
            secretKey: "config"