name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run_tests:
    uses: epam/ai-dial-ci/.github/workflows/java_pr.yml@317b262f2f055643de54287d6b8c90651b32921f
    secrets: inherit
    with:
      platforms: "linux/amd64,linux/arm64"
      java-version: 21
      trivy-limit-severities-for-sarif: false