name: PR Workflow

on:
  pull_request:
    branches: [development, release-*]

jobs:
  run_tests:
    uses: epam/ai-dial-ci/.github/workflows/java_pr.yml@2.4.1
    secrets: inherit
    with:
      platforms: "linux/amd64,linux/arm64"
      java-version: 21
      trivy-bypassed: true
