name: Release Workflow

on:
  push:
    branches: [development, release-*]
  workflow_dispatch:
    inputs:
      promote:
        type: boolean
        default: false
        description: Promote release to stable (for release-* branches only)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/java_release.yml@4.4.1
    with:
      promote: ${{ github.event_name == 'workflow_dispatch' && inputs.promote }}
      platforms: "linux/amd64,linux/arm64"
      java-version: 21
    secrets: inherit
