name: Release Workflow

on:
  push:
    branches: [development, release-*]

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/java_release.yml@2.4.1
    secrets: inherit
    with:
      platforms: "linux/amd64,linux/arm64"
      java-version: 21
