name: Release version

on:
  push:
    branches: [ development, release-* ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    uses: nepalevov/ai-dial-ci/.github/workflows/publish_gradle_docker.yml@main
    secrets: inherit
